---
language: bash
cache:
- directories:
  - "$HOME/emacs"
env:
  global:
    - EMACS_DIR=$HOME/emacs
    - EMACS_VERSION=26.1
before_install:
  # Install Emacs 26 from upstream
  - bash -e <(curl -fsSkL 'https://raw.githubusercontent.com/vermiculus/emake.el/d8ab7790f5823547fd4e7aec2218771a3dda0638/build-emacs')
  - pushd . && cd $EMACS_DIR && sudo make install && popd
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - bin/test-examples
